# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigo',
            name='codigo',
            field=models.CharField(max_length=20),
        ),
    ]
