# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20180220_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigo',
            name='codigo',
            field=models.CharField(max_length=12),
        ),
    ]
